# Generated by Django 5.0.1 on 2024-02-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
