# Generated by Django 5.0.1 on 2024-02-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_usermodel_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='doctor_specialty',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
