# Generated by Django 5.0.1 on 2024-02-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_appointmentmodel_doctor_id_appointmentmodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmodel',
            name='doctor_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
