# Generated by Django 5.0.1 on 2024-02-15 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_appointmentmodel_doctor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmodel',
            name='doctor_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
