# Generated by Django 5.0.1 on 2024-02-15 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_appointmentmodel_doctor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='doctor_specialty',
            new_name='doctor_speciality',
        ),
    ]
